const projectList = [
  {
    name: 'Voluntour Web App',
    type: 'FRONT-END PROJECT',
    tech: 'Javascript, HTML, CSS, API',
    picture: 'https://images.unsplash.com/photo-1504805572947-34fad45aed93?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=96e8c52b31b6e86b4abf5a20d9845793&auto=format&fit=crop&w=1050&q=80',
    description: 'A Web App that allows the users to search, research and book a .socially conscious travel adventure.',
    live: 'https://seaplago-team.github.io/Voluntour/',
    github: 'https://github.com/christine-aqui/Voluntour',
    collaborators: 'christine-aqui, shrekstah, usamaiqbal36, LisaFreedman',
  },
  {
    name: 'Waste-Relations',
    type: 'MOBILE FIRST PROJECT',
    tech: 'Javascript, HTML, CSS, Node, Express Handlebars, MySQL, Sequelize, Passport',
    picture: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f8b5a4a4c3548fbfc1f753ec805eca60&auto=format&fit=crop&w=1050&q=80',
    description: 'A Waste managment system that allows user to search items from a mySQL database and tells the user how to dispose of it.',
    live: 'https://wasterelations.herokuapp.com/',
    github: 'https://github.com/christine-aqui/Waste-Relations',
    collaborators: 'christine-aqui, andretqt, k4meli4, LisaFreedman',
  },
  {
    name: 'In Their Own Voices',
    type: 'FULLSTACK PROJECT',
    tech: 'Javascript, React, Node.js, MongoDB, Mongoose.js, Express.js, Passport,js',
    picture: 'https://images.unsplash.com/photo-1534322904425-1bca0e9211e8?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=13eca4d401fd7b5fac7239fb81671147&auto=format&fit=crop&w=965&q=80',
    description: '"In their own Voices" aims to allow users to easlier follow their MPP social presence and ',
    live: 'https://itow-project.herokuapp.com/',
    github: 'https://github.com/christine-aqui/lace-repo',
    collaborators: 'christine-aqui, ela-p-p, andretqt, k4meli4, LisaFreedman',
  },
  {
    name: 'Room Mate Finder',
    type: 'Demo Application',
    tech: 'Node, Express, JavaScript, CSS, animate.css',
    picture: 'https://raw.githubusercontent.com/christine-aqui/FriendFinder/master/Roommate%20Finder.gif',
    description: 'This app records results from user survey forms. The user responses are compared against those of other users. Friend finder will then search for the best overall match and return their name and photograph',
    live: 'https://roomer-01.herokuapp.com/',
    github: 'https://github.com/christine-aqui/FriendFinder',
    collaborators: 'christine-aqui',
  },
  {
    name: 'Train-Scheduler',
    type: 'Front-end Firebase App ',
    tech: 'jQuery, JavaScript, CSS, HTML, Firebase, moment',
    picture: 'https://github.com/christine-aqui/Train-Scheduler/raw/master/Train%20Scheduler.gif',
    description: 'A train schedule application that incorporates Firebase to host arrival and departure data. The app retrieves and manipulate this information with Moment.js. This website will provide up-to-date information about various trains, namely their arrival times and how many minutes remain until they arrive at their station.',
    live: 'https://christine-aqui.github.io/Train-Scheduler/',
    github: 'https://github.com/christine-aqui/Train-Scheduler',
    collaborators: 'christine-aqui',
  },
  {
    name: 'Clicky Game',
    type: 'Front-end app ',
    tech: 'React, CSS, JavaScript',
    picture: 'https://github.com/christine-aqui/clicky-game/raw/master/public/gif/app-in-motion.gif',
    description: 'Clicky Memory Game built with React',
    live: 'https://this-clicky-game.herokuapp.com/',
    github: 'https://github.com/christine-aqui/clicky-game',
    collaborators: 'christine-aqui',
  },
  {
    name: '101 Donations',
    type: 'Elevate Hackathon 2018',
    tech: 'React.js, Firebase, Bootstrap 4, Mobile-First Web App',
    picture: 'https://images.unsplash.com/photo-1526470608268-f674ce90ebd4?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=6294955020af986540d05f5d4d8391a3&auto=format&fit=crop&w=1567&q=80',
    description: 'Poverty and Waste. Two problems can be solved at once. Donate to charity. Sounds simple right? But, making a donation is often more tedious than it seems. We aim to turn donating into a seamless process, connecting people with charities and refugee camps.',
    live: 'https://donations101.herokuapp.com/',
    github: 'https://github.com/hackathon-teamTO/101-donations',
    collaborators: 'christine-aqui, andretqt, MJ3132, ParhamTaher',
  },
];

export default projectList;

// {
//   name: 'What is Lorem Ipsum?',
//   type: 'Lorem ',
//   tech: 'Lorem',
//   picture: 'https://via.placeholder.com/140x100',
//   description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
//   live: '#',
//   github:'#',
//   collaborators:'christine-aqui'
// },
